services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/Kernel.php'

    App\Ffmpeg\Convert:
        arguments:
            $projectDir: "%kernel.project_dir%"

    App\Ffmpeg\Concat:
        arguments:
            $projectDir: "%kernel.project_dir%"

    App\Character\CharacterFactory:
        arguments:
            $projectDir: "%kernel.project_dir%"

    App\Generator\CharactersListGenerator:
        arguments:
            $projectDir: "%kernel.project_dir%"

    App\Generator\DefenseGenerator:
        arguments:
            $projectDir: "%kernel.project_dir%"
