name: generate-html
permissions:
    contents: write
    pull-requests: write
on:
    workflow_dispatch: ~
jobs:
    generate-html:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6
            -
                name: Composer cache
                uses: actions/cache@v5
                with:
                    path: vendor
                    key: composer-${{ hashFiles('composer.lock') }}
                    restore-keys: composer-${{ hashFiles('composer.lock') }}
            - run: bin/ci/start
            - run: bin/ci/console generate:html
            -
                name: Create pull request
                uses: peter-evans/create-pull-request@v7
                with:
                    base: master
                    branch: generate-html
                    title: Generate HTML
                    body: ''
                    commit-message: Generate HTML
